#
# This has to be added to the main routes .yaml if the default flow routes are not present
#

##
# Monocle

-
  name:  'Monocle API'
  uriPattern: 'api/{@action}'
  defaults:
    '@package': 'Sitegeist.Monocle'
    '@subpackage': ''
    '@controller': 'Api'
    '@format': 'html'
  httpMethods: ['GET','POST']

-
  name:  'Monocle Preview - Module'
  uriPattern: 'preview/module/{ignore}'
  routeParts:
    'ignore':
      handler: 'Sitegeist\Monocle\Routing\IgnoreRoutePartHandler'
  defaults:
    '@package': 'Sitegeist.Monocle'
    '@subpackage': ''
    '@action': 'module'
    '@controller': 'Preview'
    '@format': 'html'
  httpMethods: ['GET','POST']

-
  name:  'Monocle Preview'
  uriPattern: 'preview/{@action}'
  defaults:
    '@package': 'Sitegeist.Monocle'
    '@subpackage': ''
    '@controller': 'Preview'
    '@format': 'html'
  httpMethods: ['GET','POST']
