
Sitegeist:
  Monocle:
    viewportPresets: {  }
    preview:
      defaultPath: atoms.basic
      metaViewport: ''
      additionalResources:
        styleSheets: {  }
        javaScripts: {  }
Neos:
  Flow:
    security:
      authentication:
        providers:
          Neos.Neos:Backend:
            requestPatterns:
              'Sitegeist.Monocle:monocleControllers':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'Sitegeist\Monocle\Controller\.*'
  Neos:
    modules:
      administration:
        submodules:
          monocle:
            label: Monocle
            controller: \Sitegeist\Monocle\Controller\StyleguideController
            description: 'A Styleguide implementation based on TypoScript prototypes and the idea of atomic-design'
            icon: icon-magic
            privilegeTarget: 'Sitegeist.Monocle:Backend.Styleguide'
            additionalResources:
              styleSheets:
                module: 'resource://Sitegeist.Monocle/Public/Styles/Module.css'
