
Sitegeist:
  Monocle:
    viewportPresets: {  }
    preview:
      defaultPath: atoms.basic
      metaViewport: ''
      additionalResources:
        styleSheets: {  }
        javaScripts: {  }
      structure:
        atoms:
          match: Components?\.Atom
          label: Atoms
          icon: icon-gear
          color: '#4DBCE9'
        molecules:
          match: Components?\.Molecule
          label: Molecules
          icon: icon-gears
          color: '#26ADE4'
        organisms:
          match: Components?\.Organism
          label: Organisms
          icon: icon-certificate
          color: '#D1E751'
        templates:
          match: Components?\.Template
          label: Templates
          icon: icon-file
          color: '#FFF'
        base:
          match: Components?\.Base
          label: Base
          icon: icon-minus
          color: '#AAA'

Neos:
  Flow:
    security:
      authentication:
        providers:
          Neos.Neos:Backend:
            requestPatterns:
              'Sitegeist.Monocle:monocleControllers':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'Sitegeist\Monocle\Controller\.*'
  Neos:
    modules:
      administration:
        submodules:
          monocle:
            label: Monocle
            controller: \Sitegeist\Monocle\Controller\StyleguideController
            description: 'A styleguide for fusion prototypes and the idea of components'
            icon: icon-magic
            privilegeTarget: 'Sitegeist.Monocle:Backend.Styleguide'
            additionalResources:
              styleSheets:
                module: 'resource://Sitegeist.Monocle/Public/Styles/Module.css'
